### ISSUE TITLE
cant remove or change bm-overlay style

### ISSUE THREAD

**Issue by AMNeves** [negomi/react-burger-menu#155]
I am trying to remove the default grey overlay, but cant manage to change it, i added css passed styles but nothing changes, where does it store the overlay style?

**Comment by AMNeves** [comment]
Well i fixed it with the handy noOverlay option, but its still weird i cant change it, im using meteor with react newest versions

**Comment by negomi** [comment]
Hi @AMNeves, as the overlay styles are passed inline by the component, you will need to use `!important` if you want to change the overlay styles using CSS.

For example:
```css
.bm-overlay {
  background: rgba(255, 255, 255, 0.3) !important; /* Will give you a white overlay */
}
```
