### ISSUE TITLE
Feature needed

### ISSUE THREAD

**Issue by ssageghi** [negomi/react-burger-menu#185]
Hi
can you add a feature to add Menu title under icon?

**Comment by negomi** [comment]
Hey @ssageghi, you can do this with CSS pseudo classes.

For example, this CSS:
```css
.bm-burger-button::after {
    content: 'MENU';
    position: absolute;
    top: 38px;
    font-size: 12px;
    font-weight: 700;
    color: #373a47;
}
```
will produce:

![screen shot 2017-08-29 at 9 50 59 pm](https://user-images.githubusercontent.com/3727684/29856011-e8814670-8d04-11e7-8947-47d1597e5002.png)

Does that help?
