### ISSUE TITLE
Cannot change cross button size with provided styles

### ISSUE THREAD

**Issue by verzola** [negomi/react-burger-menu#234]
Hello! I want to make the cross button size a little bit bigger and I can't seen to be able to change with the provided examples in the documentation:

```css
/* Position and sizing of clickable cross button */
.bm-cross-button {
  height: 24px;
  width: 24px;
}
```

Even by inspecting element putting !important on the bm-cross-button It didn't change the size:
![capture](https://user-images.githubusercontent.com/2985522/38177848-38a6c0ea-35dd-11e8-8851-64d18a62040e.PNG)

**Comment by negomi** [comment]
Hey @verzola,

Because the cross is made by rotating two elements to look like an X, this is an example of the CSS you would need to make a slightly bigger version:
```css
/* This positions the cross centrally in the button */
.bm-cross-button > span {
    top: 2px !important;
}

/* This targets the actual elements that make up the cross */
.bm-cross {
    width: 5px !important;
    height: 20px !important;
}
```
