### ISSUE TITLE
Vertical Scrolling

### ISSUE THREAD

**Issue by banderson5144** [negomi/react-burger-menu#28]
Will the menu scroll if there are a lot of items?

**Comment by negomi** [comment]
Not by default, but you can achieve that behaviour with:

```css
.bm-item-list {
  overflow-y: scroll;
}
```
