### ISSUE TITLE
Resizing cross doesn't work

### ISSUE THREAD

**Issue by corysimmons** [negomi/react-burger-menu#282]
Docs:

```css
/* Position and sizing of clickable cross button */
.bm-cross-button {
  height: 24px;
  width: 24px;
}
```

Changing these values (e.g. `50px`, `80px`) does nothing. Something in the code overrides it with the default `24px` values (which I'm assuming the hamburger bars are generated from).

Using `!important` doesn't help.
