### ISSUE TITLE
Menu opens when i click anywhere on screen

### ISSUE THREAD

**Issue by Daniele122898** [negomi/react-burger-menu#320]
![image](https://user-images.githubusercontent.com/20451770/56085320-45e48480-5e41-11e9-8d4c-807e5ea85feb.png)

It doesn't matter where i click it opens the menue.

```js
<div id={"outer-container"}>
   <Menu
            pageWrapId={'outer-container'}
            outerContainerId={'outer-container'}
            right 
            width={'50%'}
            customBurgerIcon={<IoMdMenu/>}
            customCrossIcon={<IoMdClose/>}
            crossButtonClassName={'cross'}
            burgerButtonClassName={'burger'}
            bodyClassName={'BODY'}
            htmlClassName={'HTML'}
            overlayClassName={'OVERLAY'}
            menuClassName={'burger-menu'}
          >
            <a href="" 
              className="button button--link burger-button"
            >
              My Requests
            </a>
            <a href="" 
              className="button button--link burger-button"
            >
              Logout
            </a>
          </Menu>
</div>
```

This is the Menu im using. I added some custom classes and the ones written in CAPS is when i tried to debug if any of these classes would be applied to that weird button. I styled the hamburger and gave him a 30px height and width but it all seems to just not work... 

```scss
.burger {
    color: white;
    height: 30px ;
    width: 30px ;
}

.cross {
    color: black;
    height: 30px !important;
    width: 30px !important;
    right: 19px !important;
    top: -5px !important;
}

.burger-menu {
    background: rgba($color: #fff, $alpha: 0.95);
    /*
    filter: blur(8px);
    -webkit-filter: blur(8px);
    */
    margin-top: -23px;
    padding: $l-size $s-size;
}

.burger-button {
    color: $dark-grey;
    border-top: 1px solid darken($off-white, $amount: 15);
}

.burger-button:first-child {
    margin-top: $l-size;
}

.burger-button:last-child {
    border-bottom: 1px solid darken($off-white, $amount: 15);
}
```

I'm a little confused as i tried many things but just can't get it to work by just clicking the hamburger icon. It's just the entire page :/

Also the div was added after to check if that fixes anything. But it didn't

**Comment by negomi** [comment]
Hi @Daniele122898, are the 30px height/width styles being overwritten by something else on your `.burger` element?

**Comment by Daniele122898** [comment]
hei @negomi sry for the late response i went to sleep after hahah

but no it doesn't seem like it is 
![image](https://user-images.githubusercontent.com/20451770/56091391-a231bd80-5eae-11e9-9cd8-fd85976815e5.png)

The button that breaks everything is right below the burger. That open menue button.

**Comment by Daniele122898** [comment]
```scss
.burger {
    color: white;
    height: 30px ;
    width: 30px ;

    button {
        position: relative !important;
        left: 0px !important;
        top: -40px !important;
    }
}
```

I added these styles to the burger class but this seems a little hacky..
